### ISSUE TITLE
Support for shared examples

### ISSUE THREAD

**Issue by liveh2o** [mmmries/rspec_rabl#11]
Currently, I don't believe RSpec RABL supports shared examples (or, at least I don't know how to use it with shared examples):

```shell
166) Accounts Views v1/accounts/account.rabl behaves like an account view
   Failure/Error: it { should render_attribute(:feed_last_payment_at).with_value(account.feed_last_payment_at.to_s) }
   RuntimeError:
     Cannot find rabl template 'behaves like an account view' within registered (["app/views"]) view paths!
   Shared Example Group: "an account view" called from ./spec/views/v1/account_views_spec.rb:189
   # ./spec/views/v1/account_views_spec.rb:148:in `block (3 levels) in <top (required)>'
```

Is there a way to manually specify the template that should be used for a spec?

**Comment by mmmries** [comment]
sweet! I've been wanting to update this gem for a while since it isn't very well structured

Currently there is no way to manually specify a template (https://github.com/mmmries/rspec_rabl/blob/e9e943f3f74de93a0f192df19df7d77b7de2da64/lib/rspec/rabl/example_group.rb#L38), but we could definitely change it to work more like how you specify the data for your template (ie. using the let mechanism). Let me see what I can cook up

**Comment by mmmries** [comment]
I wrote up a quick test that uses shared examples. I expected it to fail the way your test failed, but it actually passed. Can you take a quick look at [my branch](https://github.com/mmmries/rspec_rabl/compare/master...support_shared_examples) and see what is different about your usage of shared examples?

My guess would be that you are nesting the shared examples inside a describe block and the describe block is where rspec_rabl is trying to get the path to the template from

**Comment by liveh2o** [comment]
Well, I used `it_behaves_like`, not `include_examples`. I'll try that.

**Comment by mmmries** [comment]
@liveh2o any luck with `include_examples` I thought that those were aliases so I didn't expect that to fix it

**Comment by liveh2o** [comment]
Yes, I can confirm that using `include_examples` works, but `it_behaves_like` does not (nor does `it_should_behave_like`. It appears that these are not aliases, and do, in fact, have [different behavior](http://www.relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples#shared-examples-are-nestable-by-context):

```ruby
include_examples "name"      # include the examples in the current context
it_behaves_like "name"       # include the examples in a nested context
it_should_behave_like "name" # include the examples in a nested context
```

Based on this, I'd say we need to document how this is intended to be used. The crux of the issue is that we are relying on the describe block to determine the template that we are testing. If we provided a helper method that could be used to set the template that should be used, we could work around this:

```ruby
shared_examples "examples" do |template|
  rabl_template template

  it { should render_attribute(:guid) }
end

it_behaves_like "examples", "template_path/template.rabl"
it_should_behave_like "examples", "template_path/template.rabl"
```

We could also provide a helper method that wires up these specs so we can use shared examples:

```ruby
# Under the hood, this would create a shared example that accepts a template parameter
rabl_examples "examples" do
  it { should render_attribute(:guid) }
end

# Under the hood, this would call the shared example, passing the template parameter
it_renders "examples", "template_path/template.rabl"
it_should_render "examples", "template_path/template.rabl"
```

**Comment by mmmries** [comment]
I really liked your first example:

```ruby
shared_examples "examples" do |template|
  rabl_template template

  it { should render_attribute(:guid) }
end

it_behaves_like "examples", "users/show.rabl"
```

I'm not crazy about the `rabl_examples` + `it_renders` helper methods. We should be able to follow the pattern is used for the `rabl_data` helper method.

Do you want to take a swing at this one? I'm okay to work on it if you would rather not.
